### ISSUE TITLE
New-> <x> should allow for a BNGL basic template option

### ISSUE THREAD

**Issue by jjtapia** [RuleWorld/rulebender#168] opened 2015-08-14 20:23 UTC
Right now RuleBender allows for the creation of empty files inside a project. It should also give the option to create a file with template sections inside it. Example:

begin model
begin parameter
end parameter
...
end model

**Comment by lh64** [comment] 2015-08-16 02:48
Duplicate of issue #92

**Closed by lh64** 2015-08-16 02:48 UTC
Labels: duplicate
