### ISSUE TITLE
Block commenting in the BNGL editor.  Can this feature be added ?

### ISSUE THREAD

**Issue by rhclark** [RuleWorld/rulebender#165] opened 2015-07-23 21:20 UTC
Not sure whether or not BNGL supports block commenting (though I doubt it does), but many text editors allow one to highlight a block of code, them choose to block comment from the editor's menu. Similarly, a block can be highlighted and uncommented. Notepad++ (Windows) and Geany (Linux) are two that I've used that have this feature.

Brandon

**Comment by jjtapia** [comment] 2015-07-23 21:30
Duplicate of https://github.com/RuleWorld/rulebender/issues/138

**Closed by jjtapia** 2015-07-23 21:30 UTC
Labels: duplicate
