### ISSUE TITLE
java.lang.NullPointerException on save

### ISSUE THREAD

**Issue by jrfaeder** [RuleWorld/rulebender#195] opened 2016-06-02 19:27 UTC
In some models this error occurs when attempting to save the model. This is a nuisance but does not affect the save operation or the execution of the model in BioNetGen. The problem can be demonstrated (at least on linux with version 2.1.0.5) by uncommenting either R4 or R7 in the attached model.
[fceri_noerr.bngl.txt](https://github.com/RuleWorld/rulebender/files/296350/fceri_noerr.bngl.txt)

**Comment by rhclark** [comment] 2017-04-26 20:24
This seems to be a duplicate of Issue #202

**Comment by jczech** [comment] 2017-12-11 16:26
I can't recreate this problem on Linux with RuleBender 2.2.1. Has this been fixed? Should this issue (#195) and #202 be closed?

**Comment by jrfaeder** [comment] 2018-01-21 19:54
Seems to be resolved.

**Closed** 2018-01-21 19:53 UTC
Labels: bug
